### ISSUE TITLE
./image.go:70: cannot use app.ImageMedia literal (type *app.ImageMedia) as type app.ImageMediaCollection in argument to ctx.OK

### ISSUE THREAD

**Issue by nooproblem** [goadesign/examples#15] opened 2017-02-27 07:13 UTC
Hi,

Using goadesign/examples/gopherjs.

After `go generate` and then `go build`, the error `./image.go:70: cannot use app.ImageMedia literal (type *app.ImageMedia) as type app.ImageMediaCollection in argument to ctx.OK` is generated. I am using the most recent committed version of goadesign/examples. I don't know enough about goa design components and code generation yet to be able to debug this easily, but I would be interested to know what the resolution might be!

**Comment by raphael** [comment] 2017-02-28 21:40
Thank you for the report! the issue is fixed in `master`.

**Closed by raphael** 2017-02-28 21:40 UTC

**Comment by nooproblem** [comment] 2017-03-01 06:13
Thanks!
